// Copyright (c) 2026 Smartonlabs Inc.
// SPDX-License-Identifier: MIT

//! Independently authored from the Libertas request/response wire contract.
//! Literal vectors are frozen inputs and must not be regenerated by this
//! crate.

use libertas_matter::{
    InlineByteBuffer,
    frame::{self, EventMetadata, EventTimestamp, InvokeResponse, Operation, Report, Status},
    tlv::{Element, FromTLV, Tag, ToTLV, ValueType},
};

const CLUSTER: u32 = 0x1234;
const ITEM: u32 = 0x5678;

const COMMAND_REQUEST: &[u8] = &[
    0x15, 0x37, 0x00, 0x25, 0x01, 0x34, 0x12, 0x25, 0x02, 0x78, 0x56, 0x18, 0x35, 0x01, 0x29, 0x01,
    0x18, 0x18,
];
const COMMAND_RESPONSE: &[u8] = &[
    0x15, 0x35, 0x00, 0x37, 0x00, 0x25, 0x01, 0x34, 0x12, 0x25, 0x02, 0x78, 0x56, 0x18, 0x35, 0x01,
    0x29, 0x01, 0x18, 0x18, 0x18,
];
const COMMAND_STATUS: &[u8] = &[
    0x15, 0x35, 0x01, 0x37, 0x00, 0x25, 0x01, 0x34, 0x12, 0x25, 0x02, 0x78, 0x56, 0x18, 0x35, 0x01,
    0x24, 0x00, 0x02, 0x24, 0x01, 0x01, 0x18, 0x18, 0x18,
];
const ATTRIBUTE_WRITE: &[u8] = &[
    0x16, 0x15, 0x37, 0x01, 0x25, 0x03, 0x34, 0x12, 0x25, 0x04, 0x78, 0x56, 0x18, 0x35, 0x02, 0x29,
    0x01, 0x18, 0x18, 0x18,
];
const WRITE_STATUS: &[u8] = &[
    0x16, 0x15, 0x37, 0x00, 0x25, 0x03, 0x34, 0x12, 0x25, 0x04, 0x78, 0x56, 0x18, 0x35, 0x01, 0x24,
    0x00, 0x02, 0x24, 0x01, 0x01, 0x18, 0x18, 0x18,
];
const ATTRIBUTE_REPORT: &[u8] = &[
    0x16, 0x15, 0x35, 0x01, 0x37, 0x01, 0x25, 0x03, 0x34, 0x12, 0x25, 0x04, 0x78, 0x56, 0x18, 0x35,
    0x02, 0x29, 0x01, 0x18, 0x18, 0x18, 0x18,
];
const ATTRIBUTE_REPORT_FROM_HOST: &[u8] = &[
    0x15, 0x36, 0x01, 0x15, 0x35, 0x01, 0x37, 0x01, 0x25, 0x03, 0x34, 0x12, 0x25, 0x04, 0x78, 0x56,
    0x18, 0x35, 0x02, 0x29, 0x01, 0x18, 0x18, 0x18, 0x18, 0x18,
];
const EVENT_REPORT: &[u8] = &[
    0x16, 0x15, 0x35, 0x01, 0x37, 0x00, 0x25, 0x02, 0x34, 0x12, 0x25, 0x03, 0x78, 0x56, 0x18, 0x24,
    0x01, 0x09, 0x24, 0x02, 0x02, 0x24, 0x03, 0x0a, 0x35, 0x07, 0x29, 0x01, 0x18, 0x18, 0x18, 0x18,
];
const READ_OR_SUBSCRIBE_REQUEST_FROM_HOST: &[u8] = &[
    0x16, 0x17, 0x25, 0x03, 0x34, 0x12, 0x25, 0x04, 0x78, 0x56, 0x18, 0x18,
];
const STATUS_RESPONSE: &[u8] = &[0x02];

#[derive(Clone, Debug, Eq, PartialEq, libertas_matter::ToTLV, libertas_matter::FromTLV)]
struct Fields {
    #[tagval(1)]
    enabled: bool,
}

const STATUS: Status = Status {
    status: 2,
    cluster_status: Some(1),
};

fn fields() -> Fields {
    Fields { enabled: true }
}

#[test]
fn operation_codes_match_the_native_host_contract() {
    assert_eq!(Operation::StatusResponse as u8, 0x01);
    assert_eq!(Operation::ReadRequest as u8, 0x02);
    assert_eq!(Operation::SubscribeRequest as u8, 0x03);
    assert_eq!(Operation::SubscribeResponse as u8, 0x04);
    assert_eq!(Operation::ReportData as u8, 0x05);
    assert_eq!(Operation::WriteRequest as u8, 0x06);
    assert_eq!(Operation::WriteResponse as u8, 0x07);
    assert_eq!(Operation::InvokeRequest as u8, 0x08);
    assert_eq!(Operation::InvokeResponse as u8, 0x09);
    assert_eq!(Operation::TimedRequest as u8, 0x0a);
    assert_eq!(Operation::AttributeChanged as u8, 0xf0);
    assert_eq!(frame::PROTOCOL_MATTER, 1);
}

#[test]
fn invoke_request_vector_is_frozen() {
    let mut writer = InlineByteBuffer::new();
    frame::encode_command_request(&mut writer, CLUSTER, ITEM, &fields()).unwrap();
    assert_eq!(writer.as_slice(), COMMAND_REQUEST);

    let decoded = frame::decode_command_request(COMMAND_REQUEST).unwrap();
    assert_eq!((decoded.cluster_id, decoded.command_id), (CLUSTER, ITEM));
    assert_eq!(
        Fields::from_tlv(&decoded.fields.unwrap()).unwrap(),
        fields()
    );
}

#[test]
fn invoke_response_vectors_are_frozen() {
    let mut writer = InlineByteBuffer::new();
    frame::encode_command_response(&mut writer, CLUSTER, ITEM, &fields()).unwrap();
    assert_eq!(writer.as_slice(), COMMAND_RESPONSE);
    match frame::decode_invoke_response(COMMAND_RESPONSE).unwrap() {
        InvokeResponse::Command(command) => {
            assert_eq!((command.cluster_id, command.command_id), (CLUSTER, ITEM));
            assert_eq!(
                Fields::from_tlv(&command.fields.unwrap()).unwrap(),
                fields()
            );
        }
        response => panic!("unexpected response: {response:?}"),
    }

    writer.clear();
    frame::encode_command_status(&mut writer, CLUSTER, ITEM, STATUS).unwrap();
    assert_eq!(writer.as_slice(), COMMAND_STATUS);
    assert_eq!(
        frame::decode_invoke_response(COMMAND_STATUS).unwrap(),
        InvokeResponse::Status {
            cluster_id: CLUSTER,
            command_id: ITEM,
            status: STATUS,
        }
    );
}

#[test]
fn attribute_write_and_write_response_vectors_are_frozen() {
    let mut writer = InlineByteBuffer::new();
    frame::encode_attribute_write(&mut writer, CLUSTER, ITEM, &fields()).unwrap();
    assert_eq!(writer.as_slice(), ATTRIBUTE_WRITE);
    assert_eq!(
        Fields::from_tlv(&frame::decode_attribute_write(ATTRIBUTE_WRITE, CLUSTER, ITEM).unwrap())
            .unwrap(),
        fields()
    );

    writer.clear();
    frame::encode_write_status(&mut writer, CLUSTER, ITEM, STATUS).unwrap();
    assert_eq!(writer.as_slice(), WRITE_STATUS);
    assert_eq!(
        frame::decode_write_status(WRITE_STATUS, CLUSTER, ITEM).unwrap(),
        STATUS
    );
}

#[test]
fn report_vectors_are_frozen_in_both_host_directions() {
    let mut writer = InlineByteBuffer::new();
    frame::encode_attribute_report(&mut writer, CLUSTER, ITEM, &fields()).unwrap();
    assert_eq!(writer.as_slice(), ATTRIBUTE_REPORT);

    for encoded in [ATTRIBUTE_REPORT, ATTRIBUTE_REPORT_FROM_HOST] {
        match frame::decode_attribute_report(encoded, CLUSTER, ITEM).unwrap() {
            Report::Data(value) => {
                assert_eq!(Fields::from_tlv(&value).unwrap(), fields());
            }
            report => panic!("unexpected report: {report:?}"),
        }
    }

    writer.clear();
    frame::encode_event_report(
        &mut writer,
        CLUSTER,
        ITEM,
        EventMetadata {
            event_number: 9,
            priority: 2,
            timestamp: EventTimestamp::Epoch(10),
        },
        &fields(),
    )
    .unwrap();
    assert_eq!(writer.as_slice(), EVENT_REPORT);
    match frame::decode_event_report(EVENT_REPORT, CLUSTER, ITEM).unwrap() {
        Report::Data(value) => assert_eq!(Fields::from_tlv(&value).unwrap(), fields()),
        report => panic!("unexpected report: {report:?}"),
    }
}

#[test]
fn native_status_and_read_subscribe_callback_vectors_are_frozen() {
    assert_eq!(STATUS_RESPONSE, &[2]);

    let root = Element::from_bytes(READ_OR_SUBSCRIBE_REQUEST_FROM_HOST).unwrap();
    assert_eq!(root.value_type(), ValueType::Array);
    let path = root.children().unwrap().read_element().unwrap().unwrap();
    assert_eq!(path.value_type(), ValueType::List);
    assert_eq!(path.context(3).unwrap().u32().unwrap(), CLUSTER);
    assert_eq!(path.context(4).unwrap().u32().unwrap(), ITEM);
    assert!(root.children().unwrap().read_element().unwrap().is_some());
}

#[test]
fn derive_macros_call_the_writer_directly_and_round_trip_owned_data() {
    let mut writer = InlineByteBuffer::new();
    fields().to_tlv(Tag::Anonymous, &mut writer).unwrap();
    let element = Element::from_bytes(writer.as_slice()).unwrap();
    assert_eq!(Fields::from_tlv(&element).unwrap(), fields());
}
