// Copyright (c) 2026 Smartonlabs Inc.
// SPDX-License-Identifier: MIT

//! Independently authored from the Matter Core TLV element table and examples.
//! Expected bytes in this file must never be regenerated by the Rust encoder.

use libertas_matter::{
    InlineByteBuffer,
    error::Error,
    tlv::{Element, FromTLV, Nullable, SliceWriter, TLVWrite, Tag, ToTLV, ValueType},
};

const TYPE_VECTORS: &[(ValueType, &[u8])] = &[
    (ValueType::Signed8, &[0x00, 0x80]),
    (ValueType::Signed16, &[0x01, 0x7f, 0xff]),
    (ValueType::Signed32, &[0x02, 0xff, 0x7f, 0xff, 0xff]),
    (
        ValueType::Signed64,
        &[0x03, 0xff, 0xff, 0xff, 0x7f, 0xff, 0xff, 0xff, 0xff],
    ),
    (ValueType::Unsigned8, &[0x04, 0x2a]),
    (ValueType::Unsigned16, &[0x05, 0x00, 0x01]),
    (ValueType::Unsigned32, &[0x06, 0x00, 0x00, 0x01, 0x00]),
    (
        ValueType::Unsigned64,
        &[0x07, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00],
    ),
    (ValueType::BooleanFalse, &[0x08]),
    (ValueType::BooleanTrue, &[0x09]),
    (ValueType::Float32, &[0x0a, 0x00, 0x00, 0x80, 0x3f]),
    (
        ValueType::Float64,
        &[0x0b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x3f],
    ),
    (ValueType::Utf8_1, &[0x0c, 0x00]),
    (ValueType::Utf8_2, &[0x0d, 0x00, 0x00]),
    (ValueType::Utf8_4, &[0x0e, 0x00, 0x00, 0x00, 0x00]),
    (
        ValueType::Utf8_8,
        &[0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    ),
    (ValueType::Bytes1, &[0x10, 0x00]),
    (ValueType::Bytes2, &[0x11, 0x00, 0x00]),
    (ValueType::Bytes4, &[0x12, 0x00, 0x00, 0x00, 0x00]),
    (
        ValueType::Bytes8,
        &[0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    ),
    (ValueType::Null, &[0x14]),
    (ValueType::Structure, &[0x15, 0x18]),
    (ValueType::Array, &[0x16, 0x18]),
    (ValueType::List, &[0x17, 0x18]),
    (ValueType::EndOfContainer, &[0x18]),
];

#[test]
fn decodes_every_matter_tlv_element_type() {
    for &(expected_type, encoded) in TYPE_VECTORS {
        let element = Element::from_bytes(encoded).unwrap();
        assert_eq!(element.value_type(), expected_type, "{encoded:02x?}");
        assert_eq!(element.encoded(), encoded);
    }
}

#[test]
fn writes_canonical_scalar_vectors() {
    type ScalarVector = (&'static [u8], fn(&mut InlineByteBuffer));
    let cases: &[ScalarVector] = &[
        (&[0x08], |writer| {
            writer.bool(Tag::Anonymous, false).unwrap()
        }),
        (&[0x09], |writer| writer.bool(Tag::Anonymous, true).unwrap()),
        (&[0x00, 0x2a], |writer| {
            writer.i32(Tag::Anonymous, 42).unwrap()
        }),
        (&[0x00, 0xef], |writer| {
            writer.i32(Tag::Anonymous, -17).unwrap()
        }),
        (&[0x04, 0x2a], |writer| {
            writer.u64(Tag::Anonymous, 42).unwrap()
        }),
        (&[0x01, 0x00, 0x01], |writer| {
            writer.i32(Tag::Anonymous, 256).unwrap()
        }),
        (&[0x05, 0x00, 0x01], |writer| {
            writer.u32(Tag::Anonymous, 256).unwrap()
        }),
        (&[0x0a, 0x00, 0x00, 0x80, 0x3f], |writer| {
            writer.f32(Tag::Anonymous, 1.0).unwrap()
        }),
        (
            &[0x0b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x3f],
            |writer| writer.f64(Tag::Anonymous, 1.0).unwrap(),
        ),
        (&[0x0c, 0x05, b'h', b'e', b'l', b'l', b'o'], |writer| {
            writer.utf8(Tag::Anonymous, "hello").unwrap()
        }),
        (&[0x10, 0x03, 0xaa, 0xbb, 0xcc], |writer| {
            writer.bytes(Tag::Anonymous, &[0xaa, 0xbb, 0xcc]).unwrap()
        }),
        (&[0x14], |writer| writer.null(Tag::Anonymous).unwrap()),
        (&[0x15, 0x18], |writer| {
            writer.start_struct(Tag::Anonymous).unwrap();
            writer.end_container().unwrap();
        }),
        (&[0x16, 0x18], |writer| {
            writer.start_array(Tag::Anonymous).unwrap();
            writer.end_container().unwrap();
        }),
        (&[0x17, 0x18], |writer| {
            writer.start_list(Tag::Anonymous).unwrap();
            writer.end_container().unwrap();
        }),
    ];

    for &(expected, encode) in cases {
        let mut writer = InlineByteBuffer::new();
        encode(&mut writer);
        assert_eq!(writer.as_slice(), expected);
    }
}

#[test]
fn writes_every_tag_control() {
    let vectors: &[(Tag, &[u8])] = &[
        (Tag::Anonymous, &[0x04, 0x2a]),
        (Tag::Context(0x12), &[0x24, 0x12, 0x2a]),
        (Tag::CommonProfile16(0x1234), &[0x44, 0x34, 0x12, 0x2a]),
        (
            Tag::CommonProfile32(0x1234_5678),
            &[0x64, 0x78, 0x56, 0x34, 0x12, 0x2a],
        ),
        (Tag::ImplicitProfile16(0x1234), &[0x84, 0x34, 0x12, 0x2a]),
        (
            Tag::ImplicitProfile32(0x1234_5678),
            &[0xa4, 0x78, 0x56, 0x34, 0x12, 0x2a],
        ),
        (
            Tag::FullyQualified16 {
                vendor_id: 0x1234,
                profile_number: 0x5678,
                tag: 0x9abc,
            },
            &[0xc4, 0x34, 0x12, 0x78, 0x56, 0xbc, 0x9a, 0x2a],
        ),
        (
            Tag::FullyQualified32 {
                vendor_id: 0x1234,
                profile_number: 0x5678,
                tag: 0x9abc_def0,
            },
            &[0xe4, 0x34, 0x12, 0x78, 0x56, 0xf0, 0xde, 0xbc, 0x9a, 0x2a],
        ),
    ];

    for &(tag, expected) in vectors {
        let mut writer = InlineByteBuffer::new();
        writer.u8(tag, 42).unwrap();
        assert_eq!(writer.as_slice(), expected);
        assert_eq!(Element::from_bytes(expected).unwrap().tag(), tag);
    }
}

struct FailsAfterWrite;

impl ToTLV for FailsAfterWrite {
    fn to_tlv<W: TLVWrite + ?Sized>(&self, tag: Tag, writer: &mut W) -> Result<(), Error> {
        writer.u8(tag, 7)?;
        Err(Error::Constraint)
    }
}

#[derive(libertas_matter::ToTLV)]
struct CompositeFailure {
    first: u8,
    second: FailsAfterWrite,
}

#[derive(Debug, Eq, PartialEq, libertas_matter::FromTLV, libertas_matter::ToTLV)]
struct DerivedU8(u8);

#[test]
fn derived_composites_roll_back_inline_byte_buffer() {
    let mut writer = InlineByteBuffer::new();
    writer.u8(Tag::Anonymous, 99).unwrap();
    let before = writer.as_slice().to_vec();

    assert_eq!(
        CompositeFailure {
            first: 1,
            second: FailsAfterWrite,
        }
        .to_tlv(Tag::Anonymous, &mut writer),
        Err(Error::Constraint)
    );
    assert_eq!(writer.as_slice(), before);
}

#[test]
fn fixed_slice_writer_rolls_back_when_capacity_is_exhausted() {
    let mut storage = [0_u8; 5];
    let mut writer = SliceWriter::new(&mut storage);
    writer.u8(Tag::Anonymous, 99).unwrap();
    let before = writer.as_slice().to_vec();

    let result = libertas_matter::tlv::transaction(&mut writer, |writer| {
        writer.start_struct(Tag::Anonymous)?;
        writer.u32(Tag::Context(1), 0x1_0000)?;
        writer.end_container()
    });
    assert_eq!(result, Err(Error::NoSpace));
    assert_eq!(writer.as_slice(), before);
}

#[test]
fn derived_newtypes_preserve_nullable_scalar_constraints() {
    let mut writer = InlineByteBuffer::new();
    assert_eq!(
        Nullable::Value(DerivedU8(u8::MAX)).to_tlv(Tag::Anonymous, &mut writer),
        Err(Error::Constraint)
    );
    assert!(writer.is_empty());

    let element = Element::from_bytes(&[0x04, u8::MAX]).unwrap();
    assert_eq!(
        Nullable::<DerivedU8>::from_tlv(&element),
        Err(Error::Constraint)
    );
}

#[test]
fn rejects_truncation_and_unbalanced_containers() {
    assert_eq!(Element::from_bytes(&[0x05, 0x01]), Err(Error::Truncated));
    assert_eq!(
        Element::from_bytes(&[0x15, 0x04, 0x01]),
        Err(Error::Truncated)
    );
    assert_eq!(
        Element::from_bytes(&[0x15, 0x38, 0x00]),
        Err(Error::Malformed)
    );
}
